name: modrinth_api
version: 0.1.0
description: An unofficial Modrinth library for Dart.
repository: https://github.com/hihiqy1/modrinth_api_dart
issue_tracker: https://github.com/hihiqy1/modrinth_api_dart/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.5
  collection: ^1.17.1

dev_dependencies:
  lints: ^2.0.1