name: modrinth_api
version: 0.0.1
description: An unofficial Modrinth library for Dart.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.5
  collection: ^1.17.1

dev_dependencies:
  lints: ^2.0.1